import mne
import os
import matplotlib.pyplot as plt
import numpy as np
from vmdpy import VMD
import EntropyHub as EH

# ========================================== Read File ==========================================
file_path = os.path.join("chbmit_dataset/chb03", "chb03_01.edf")

# Load the raw data (added verbose='ERROR' to keep your terminal clean)
raw = mne.io.read_raw_edf(file_path, preload=True, verbose='ERROR')
print("\n--- Channels ---")
print(raw.ch_names)

# ========================================== Preprocessing ==========================================
powerline_frequency = [60.0]
raw.notch_filter(freqs=powerline_frequency, verbose='ERROR')
raw.filter(l_freq=1.0, h_freq=40.0, verbose='ERROR')

# Epoching
epoch_duration = 2.0
epochs = mne.make_fixed_length_epochs(raw, duration=epoch_duration, preload=True, verbose='ERROR')
print(f"Data shape: {epochs.get_data().shape} -> (Number of Epochs, Channels, Timepoints)")
data_matrix = epochs.get_data()

# ========================================== VMD ==========================================
print("\n========================================  VMD  ========================================\n")
channel_name = 'FP1-F7'
ch_idx = epochs.ch_names.index(channel_name)

# Extract the 1D signal array for the FIRST epoch
signal = data_matrix[0, ch_idx, :]
times = epochs.times

alpha, tau, K, DC, init, tol = 2000, 0.0, 8, 0, 1, 1e-7

print(f"Parameters: alpha={alpha}, tau={tau}, K={K}, DC={DC}, init={init}, tol={tol}")

print("\nRunning VMD...")
u, u_hat, omega = VMD(signal, alpha, tau, K, DC, init, tol)

# Plot the modes
plt.figure(figsize=(10, 8))
plt.subplot(K+1, 1, 1)
plt.plot(times, signal)
plt.title('Original Signal')

for i in range(K):
    plt.subplot(K+1, 1, i+2)
    plt.plot(times, u[i])
    plt.title(f"Mode {i+1} IMF")

plt.tight_layout()
plt.show(block=False)
plt.pause(0.1)

# ========================================== Entropy Feature Extraction ==========================================
print("\n========================================  ENTROPY FEATURE EXTRACTION  ========================================\n")

# Loop through every single mode (IMF) generated by VMD
for i in range(K):
    # Extract specific mode
    imf = u[i]
    
    # Calculate tolerance dynamically for specific mode
    tolerance = 0.2 * np.std(imf)
    
    # 1. Sample Entropy
    samp_en_values, _, _ = EH.SampEn(imf, m=2, r=tolerance)
    samp_en_feature = samp_en_values[-1]
    
    # 2. Fuzzy Entropy
    fuzz_en_values, _, _ = EH.FuzzEn(imf, m=2, r=(tolerance, 2))
    fuzz_en_feature = fuzz_en_values[-1]
    
    # 3. Permutation Entropy
    perm_results = EH.PermEn(imf, m=3)
    perm_en_values = perm_results[0]
    perm_en_feature = perm_en_values[-1]
    
    print(f"\n--- Mode {i+1} ---")
    print(f"  Sample Entropy: {samp_en_feature:.4f}")
    print(f"  Fuzzy Entropy:  {fuzz_en_feature:.4f}")
    print(f"  Permut Entropy: {perm_en_feature:.4f}")

plt.show()